### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by ztl-35** [zxlzr/FewShotNLP#5]
Could you please write steps to run this code and tell us the meaning of these python files? You just upload your code and don't write anything to explain it.

**Comment by VivianYWY** [comment]
> Could you please write steps to run this code and tell us the meaning of these python files? You just upload your code and don't write anything to explain it.

hello~ have figured out how to use this code ? i also would like to run it but do not know how to deal with it. thanks very much

**Comment by zxlzr** [comment]
Sorry for the late reply. Feel free to run the script ARSC_pretrain.sh. Some hyper-parameters should be carefully tuned.
