### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Wangpeiyi9979** [zxlzr/FewShotNLP#6]
您好，请问这里：为什么do eval的时候，还要train模型呢？以及eval的数据，是用来测试的4类里的数据吗？
![image](https://user-images.githubusercontent.com/42565075/100334257-7ecd6f00-300e-11eb-9395-2d0bb7f2b6d9.png)

**Comment by VivianYWY** [comment]
> 您好，请问这里：为什么do eval的时候，还要train模型呢？以及eval的数据，是用来测试的4类里的数据吗？
> ![image](https://user-images.githubusercontent.com/42565075/100334257-7ecd6f00-300e-11eb-9395-2d0bb7f2b6d9.png)

您好～ 请问您弄清楚怎么运行这份code吗 我想复现一下但是不太确定如何开始 特别是参数里的--bert model和具体的data是如何弄的 非常感谢

**Comment by zxlzr** [comment]
您好，您可以先阅读一下论文https://arxiv.org/abs/1703.03400, 我们的方法基本基于MAML实现的，这里还有一个中文博客https://zhuanlan.zhihu.com/p/66926599，感谢关注。
