### ISSUE TITLE
怎么使用这份code

### ISSUE THREAD

**Issue by VivianYWY** [zxlzr/FewShotNLP#7]
您好，请问怎么使用这份code呢，我想运行一下，但是不知道如何开始，是否方便告知一下如何使用这些脚本文件，不胜感激

**Comment by zxlzr** [comment]
抱歉回复晚了，您可以运行ARSC_pretrain.sh来进行实验，由于时间太久了我记不太清楚具体一些超参数细节了，您有任意问题欢迎提问。
